#!/bin/sh -

INPUT="$1"
MATCH='^\([0-9.]*\): \[[Full ]*GC[^0-9]*\([0-9]*\)\([KM]\)->\([0-9]*\)\([KM]\)([0-9]*[KM])[0-9.]*, \([0-9.]*\) secs\].*$'

grep -v "$MATCH" "$INPUT" | grep -- '->' | sed 's/^/ERROR: unknown log file fmt: /'

grep "$MATCH" "$INPUT" | \
    sed -e "s/${MATCH}/\1 \2 \3 \4 \5 \6/" -e 's/K/1/g' -e 's/M/1024/g' | \
    awk 'BEGIN {t=1} {t=$1; k+=$2*$3-$4*$5; s+=$6} $6>m {m=0+$6} END {
        printf("--- %'"'"'d MB collected in %0.3f secs (%0.1f%% of total), longest GC took %0.3f secs\n", k/1024, s, 100*s/t, m)
        print "DATA gc:  total_k " k "  total_secs " s "  max_secs " m
      }'
